<?php

namespace Oxygen\ContactBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TitleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TitleRepository extends EntityRepository
{
  public function getAsArray(){
    $contacts = $this->getEntityManager()
            ->createQuery('SELECT t FROM OxygenContactBundle:Title t')
            ->getArrayResult();
    $contact_array = array();
    foreach ($contacts as $contact) {
      $contact_array[$contact['id']] = $contact['name'];
    }
    return $contact_array;
  }
}